name: newtest1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Theming
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.0.0
  photo_view: ^0.14.0
  collection: ^1.18.0

  # State Management
  flutter_riverpod: ^2.4.9
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^19.2.0

  # Cryptography & Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.2
  cryptography: ^2.5.0

  # Database
  sembast: ^3.6.0
  sembast_web: ^2.2.0
  url_launcher: ^6.1.14

  # Firebase
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  permission_handler: ^11.0.1
  animated_text_kit: ^4.2.2
  logger: ^2.0.1
  share_plus: ^7.2.1
  universal_html: ^2.2.4
  image: ^4.0.17
  device_info_plus: ^9.1.1
  mime: ^1.0.6
  path: ^1.9.0
  connectivity_plus: ^6.1.4
  video_player: ^2.9.5
  open_file: ^3.5.10
  file_picker: ^10.1.9  
  dio: ^5.8.0+1
  package_info_plus: ^8.3.0
  audioplayers: ^6.4.0
  cached_network_image: ^3.3.1
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3+1
  camera: ^0.10.5+5
  location: ^5.0.3
  battery_plus: ^6.2.1
  flutter_jailbreak_detection: ^1.10.0
  installed_apps: ^1.6.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
